### ISSUE TITLE
A new theme to be included

### ISSUE THREAD

**Issue by mhtb32** [martinbjeldbak/ultimate-beamer-theme-list#16]
I found a theme not included in your list which is beautiful and minimalistic:
[focus](https://github.com/elauksap/focus-beamertheme)

**Comment by martinbjeldbak** [comment]
I would love to include this cool theme @mhtb32! Would you be interested in submitting a PR to add it?

**Comment by mhtb32** [comment]
Yes, I am. I will make a pull request.

**Comment by martinbjeldbak** [comment]
Closed via #18
