### ISSUE TITLE
Image Previews

### ISSUE THREAD

**Issue by martinbjeldbak** [martinbjeldbak/ultimate-beamer-theme-list#20]
I would love image previews in the repository, similar to this fork: https://github.com/hamaluik/ultimate-beamer-theme-list/tree/image_previews

@hamaluik love your work. Any chance you'd be interested in opening a PR with your branch? Appreciate it 👍 !

**Comment by hamaluik** [comment]
Sure! That was the intention all along, I just haven't had time to finish. I can definitely PR in its current state however.

**Comment by martinbjeldbak** [comment]
Closing as stale, though keen to add this, just not sure how to in a sustainable way
