### ISSUE TITLE
outdated link

### ISSUE THREAD

**Issue by MauritsvanderZee** [martinbjeldbak/ultimate-beamer-theme-list#27]
Dear @martinbjeldbak ,

the following link of your list is outdated:

`
See the related blog post here [bunsen-web]
`
`
[bunsen-web]: http://www.drbunsen.org/designing-a-beamer-template-theme/
`

Best regards,
Maurits

**Comment by martinbjeldbak** [comment]
Hi @MauritsvanderZee thanks very much for letting me know. I have removed the link in #28

If you are still interested in reading about the theme, the blog post can be found here: https://web.archive.org/web/20160304232800/http://www.drbunsen.org/designing-a-beamer-template-theme/
