### ISSUE TITLE
Arguelles link broken

### ISSUE THREAD

**Issue by mcp292** [martinbjeldbak/ultimate-beamer-theme-list#38]
Use:
https://github.com/piazzai/arguelles/blob/master/demo/demo-arguelles.pdf

Or permalink:
https://github.com/piazzai/arguelles/blob/0fb521e2e5799bcc2ca3964f7d3cff272e0cced0/demo/demo-arguelles.pdfhttps://github.com/piazzai/arguelles/blob/0fb521e2e5799bcc2ca3964f7d3cff272e0cced0/demo/demo-arguelles.pdfhttps://github.com/piazzai/arguelles/blob/0fb521e2e5799bcc2ca3964f7d3cff272e0cced0/demo/demo-arguelles.pdf

**Comment by martinbjeldbak** [comment]
Thanks for pointing this out @mcp292! Now fixed via c9e380922d6bb55cf0a49d629e712454b13ea7f2
